### ISSUE TITLE
extenders 

### ISSUE THREAD

**Issue by gilbertohasnofb** [lyp-packages/auto-extenders#1]
`\autoextenders` are forcing extenders on syllables under a single note. See example below:

```
A = {
  c'2( d' 
  c'1) 
  d'2( e' 
  f') r
  c'2( d' 
  c'1) 
  d'2^"*" r
  e'4( f' g'2) 
  r2 a'
  \acciaccatura {d''8} bes'2 g'^"*"
}

B = \lyricmode { 
  \autoextenders {
    Co -- me, co -- me back in -- si -- de
  }
}

<<
  \A
  \addlyrics \B
>>
```

This outpus:

![screenshot from 2017-04-24 23 12 01](https://cloud.githubusercontent.com/assets/5700795/25358970/a62c8cd2-2943-11e7-8afe-e901a2d9404a.png)

Normally the notes marked with an * would not have an extender in the lyrics

**Comment by gilbertohasnofb** [comment]
Just adding one piece of information: it seems to me that your code is treating any group of notes as a melisma, including a group with a single note, which is probably why the extenders are being added to single notes.

**Comment by noteflakes** [comment]
As explained in the [README](https://github.com/lyp-packages/auto-extenders#readme), this code was copied verbatim from a lilypond-dev discussion. I haven't been following the lilypond mailing lists in a while, but that would probably be the best place to look for a solution.

Sorry I can't help you more with that...

**Comment by gilbertohasnofb** [comment]
@ciconia Oh, I see. I will contact the author in the list then, thanks for your reply.
